# Generated by Django 3.1.4 on 2020-12-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_nav', models.CharField(default='', max_length=100)),
                ('code', models.TextField()),
                ('color', models.CharField(default='', max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_product', to='nav.nav')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
